### PR TITLE
made nicer add members form

### PR DESCRIPTION
**Pull request by nimmerman**
@zhanghan177

### CODE REVIEW

**Comment by nimmerman** [comment]
For issue #7

**Comment by zhanghan177** [comment]
Your changes seem legit to me. And I think you did a great job in combining the two forms.

**Comment by nimmerman** [comment]
I also can't send emails, I'll look into it

**Comment by zhanghan177** [comment]
My guess is that the actual server is sitting inside umich network, so that it can connects to umich mail server to send emails. However, those servers might don't want to accept connections outside of umich networks.

**Pull request merged**
