### PR TITLE
delete electee object when converting an electee to an active

### PR DESCRIPTION
**Pull request by nimmerman**

### CODE REVIEW

**Comment by nimmerman** [comment]
@zhanghan177 Please take a look, I think we should delete the electee object when converting a member

**Comment by nimmerman** [comment]
For issue #6

**Comment by zhanghan177** [comment]
I'll take a look when I get back later today. Thanks for pointing it out. 

-Han

**Comment by zhanghan177** [comment]
Agreed. Should remove their records after they converted into active. By the way, would you mind explain what ```on_delete=models.CASCADE``` does?

**Comment by nimmerman** [comment]
It means that if the Member object that is pointed to by the OneToOne field in the Electee object is deleted than the Electee object will also be deleted.

**Pull request merged**
